version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rivalsgg-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - rivalsgg-network

  rivalsgg-api:
    image: ricks95/rivalsgg-api:latest
    container_name: rivalsgg-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    networks:
      - rivalsgg-network

  watchtower:
    image: containrrr/watchtower:latest
    container_name: rivalsgg-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300 
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  sqlserver_data:


networks:
  rivalsgg-network:
    driver: bridge