    - name: Generate Coverage Reports 
      run: |
        echo "Searching for TestResults directories anywhere in the repo:"
        find . -name "TestResults" -type d
        
        echo "Searching for coverage XML files anywhere:"
        COVERAGE_FILES=$(find . -name "*coverage*.xml" -type f)
        echo "Found coverage files: $COVERAGE_FILES"
        
        if [ -n "$COVERAGE_FILES" ]; then
          mkdir -p ./TestResults/CoverageReport
          
          echo "Generating coverage report using found files..."
          reportgenerator \
            -reports:"$(find . -name "*coverage*.xml" -type f | tr '\n' ';')" \
            -targetdir:"./TestResults/CoverageReport" \
            -reporttypes:"Cobertura;Html" \
            -verbosity:Info
            
          echo "Coverage report generated. Contents:"
          ls -la ./TestResults/CoverageReport/ || echo "CoverageReport directory not found"
        else
          echo "No coverage files found anywhere in the repository"
          echo "Full directory tree:"
          find . -type f -name "*.xml" | head -20
        finame: .NET CI/CD with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ricks95/rivalsgg-api

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Find solution or project files
      run: find . -name "*.sln" -o -name "*.csproj"
      
    - name: Restore dependencies
      run: |
        # Locate the solution or main project file
        SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
        if [ -z "$SOLUTION_FILE" ]; then
          # If no solution file, try to find the main project file
          PROJECT_FILE=$(find . -name "*.csproj" | head -n 1)
          if [ -z "$PROJECT_FILE" ]; then
            echo "No .sln or .csproj file found"
            exit 1
          fi
          dotnet restore "$PROJECT_FILE"
        else
          dotnet restore "$SOLUTION_FILE"
        fi
    
    - name: Build
      run: |
        SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
        if [ -z "$SOLUTION_FILE" ]; then
          PROJECT_FILE=$(find . -name "*.csproj" | head -n 1)
          dotnet build "$PROJECT_FILE" --no-restore
        else
          dotnet build "$SOLUTION_FILE" --no-restore
        fi
    
    - name: Test with Coverage
      run: |
        # Debug: Show current directory and structure
        echo "Current working directory: $(pwd)"
        echo "Repository structure:"
        find . -maxdepth 2 -type f -name "*.csproj" -o -name "*.sln"
        
        # Find test projects
        TEST_PROJECTS=$(find . -name "*Test*.csproj")
        echo "Found test projects: $TEST_PROJECTS"
        
        if [ -z "$TEST_PROJECTS" ]; then
          echo "No test projects found, skipping tests"
        else
          # Use the repository root for TestResults (not inside test project)
          RESULTS_DIR="$(pwd)/TestResults"
          echo "Results will be saved to: $RESULTS_DIR"
          
          # Run tests with coverage for the solution
          SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
          echo "Using solution file: $SOLUTION_FILE"
          
          if [ -n "$SOLUTION_FILE" ]; then
            echo "Running tests with coverage on solution..."
            dotnet test "$SOLUTION_FILE" \
              --no-build \
              --verbosity normal \
              --collect:"XPlat Code Coverage" \
              --results-directory "$RESULTS_DIR"
          else
            # Fallback to individual test projects  
            for TEST_PROJECT in $TEST_PROJECTS; do
              echo "Testing $TEST_PROJECT"
              dotnet test "$TEST_PROJECT" \
                --no-build \
                --verbosity normal \
                --collect:"XPlat Code Coverage" \
                --results-directory "$RESULTS_DIR"
            done
          fi
          
          # Debug: Show what was actually generated anywhere
          echo "Searching for any TestResults directories:"
          find . -name "TestResults" -type d
          echo "Searching for any coverage XML files:"
          find . -name "*coverage*.xml" -type f
        fi

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Generate Coverage Reports
      run: |
        echo "Checking for TestResults directory..."
        if [ -d "./TestResults" ]; then
          echo "TestResults directory found. Contents:"
          find TestResults -type f -name "*.xml"
          
          echo "Looking for coverage files..."
          find TestResults -name "*coverage*.xml" -type f
          
          echo "Generating coverage report..."
          reportgenerator \
            -reports:"TestResults/**/coverage.cobertura.xml" \
            -targetdir:"TestResults/CoverageReport" \
            -reporttypes:"Cobertura;Html" \
            -verbosity:Info
            
          echo "Coverage report generated. Contents:"
          ls -la TestResults/CoverageReport/ || echo "CoverageReport directory not found"
        else
          echo "No TestResults directory found, skipping coverage report generation"
          echo "Current directory contents:"
          ls -la
        fi

    - name: Upload Coverage to Codacy
      if: env.CODACY_PROJECT_TOKEN != null
      run: |
        echo "Searching for coverage files..."
        COVERAGE_FILES=$(find . -name "*coverage*.xml" -type f)
        echo "Found coverage files: $COVERAGE_FILES"
        
        if [ -n "$COVERAGE_FILES" ]; then
          # Set up Codacy environment variable
          export CODACY_PROJECT_TOKEN="${{ secrets.CODACY_PROJECT_TOKEN }}"
          
          # Use Codacy's official coverage reporter
          echo "Downloading and running Codacy Coverage Reporter..."
          bash <(curl -Ls https://coverage.codacy.com/get.sh)
        else
          echo "No coverage files found, skipping Codacy upload"
        fi
      continue-on-error: true

    - name: Upload Coverage to Codacy (Alternative)
      if: failure() && env.CODACY_PROJECT_TOKEN != null
      run: |
        echo "Alternative method failed - Codacy's official reporter should have worked above"
      continue-on-error: true
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-coverage-results
        path: TestResults/
        retention-days: 30

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          MARVEL_API_KEY=${{ secrets.MARVEL_API_KEY }}